apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 80             # The port Kubernetes service listens on
      targetPort: 5000      # The port your application listens on inside the container
      nodePort: 30007       # Specify a NodePort 
  type: NodePort            # Expose the service via a NodePort to make it accessible externally
